spring:
  datasource:
    url: jdbc:mysql://localhost:3036/lms
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:  
    hibernate:
      dialect : org.hibernate.dialect.MySQL5Dialect
      ddl-auto: create
